development:
  adapter: postgresql
  encoding: unicode
  database: pusher_chat_development
  pool: 5
  username: pusher_chat
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: pusher_chat_test
  pool: 5
  username: pusher_chat
  password: password1