development:
  adapter: postgresql
  encoding: unicode
  database: pusherChat_development
  pool: 5
  username: pusherChat
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: pusherChat_test
  pool: 5
  username: pusherChat
  password: password1